# Kafka Configuration for Industrial Sensor Data Streaming

kafka:
  # Bootstrap servers
  bootstrap_servers:
    - "localhost:9092"
    - "localhost:9093"
    - "localhost:9094"
  
  # Producer settings
  producer:
    acks: "all"                    # Wait for all replicas to acknowledge
    retries: 3                     # Number of retries
    batch_size: 16384             # Batch size in bytes
    linger_ms: 10                 # Wait time for batching
    buffer_memory: 33554432       # Buffer memory in bytes
    compression_type: "gzip"      # Compression type
    key_serializer: "org.apache.kafka.common.serialization.StringSerializer"
    value_serializer: "org.apache.kafka.common.serialization.StringSerializer"
  
  # Consumer settings
  consumer:
    group_id: "sensor-data-consumer"
    auto_offset_reset: "latest"   # earliest, latest, none
    enable_auto_commit: true
    auto_commit_interval_ms: 1000
    session_timeout_ms: 30000
    max_poll_records: 500
    key_deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    value_deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
  
  # Topic configuration
  topics:
    sensor_data:
      name: "sensor-data"
      partitions: 3
      replication_factor: 1
      config:
        retention_ms: 604800000    # 7 days
        segment_ms: 86400000       # 1 day
        compression_type: "gzip"
    
    anomalies:
      name: "anomaly-alerts"
      partitions: 1
      replication_factor: 1
      config:
        retention_ms: 2592000000   # 30 days
        segment_ms: 86400000       # 1 day
    
    maintenance:
      name: "maintenance-events"
      partitions: 1
      replication_factor: 1
      config:
        retention_ms: 2592000000   # 30 days
        segment_ms: 86400000       # 1 day

# Schema Registry (if using Confluent Schema Registry)
schema_registry:
  url: "http://localhost:8081"
  auto_register_schemas: true
  subject_name_strategy: "TopicNameStrategy"

# Monitoring and metrics
monitoring:
  enable_metrics: true
  metrics_topic: "sensor-metrics"
  health_check_interval: 30       # seconds
